[phases.setup]
providers = ["node"]
nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.install]
cmds = ["npm ci"]

[phases.build] 
cmds = ["npm run build"]

[phases.start]
cmd = "npx serve dist -s -l $PORT"

[variables]
NODE_VERSION = "18"
NPM_CONFIG_PRODUCTION = "false"