[phases.setup]
providers = ["node"]

[phases.install]
cmds = ["npm ci"]

[phases.build] 
cmds = ["npm run build"]

[phases.start]
cmd = "npx serve dist -s -l $PORT"

[variables]
NODE_VERSION = "18"

# Force Node.js detection and ignore Deno files
[providers.node]
version = "18"

[providers.deno]
enabled = false